// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/login","id":"1"},"2":{"path":"/403","id":"2"},"3":{"path":"/","id":"3"},"4":{"path":"/","parentId":"3","id":"4"},"5":{"path":"/profile","parentId":"3","id":"5"},"6":{"path":"/users","parentId":"3","id":"6"},"7":{"path":"/users/:id","parentId":"3","id":"7"},"8":{"path":"/users/:id/sessions","parentId":"3","id":"8"},"9":{"path":"/users/:id/login-history","parentId":"3","id":"9"},"10":{"path":"/audit-logs","parentId":"3","id":"10"},"11":{"path":"*","id":"11"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__login__index" */'@/pages/login/index.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__403" */'@/pages/403.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "layouts__AdminLayout" */'@/layouts/AdminLayout.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__dashboard__index" */'@/pages/dashboard/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__profile__index" */'@/pages/profile/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__users__index" */'@/pages/users/index.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__users__detail" */'@/pages/users/detail.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__users__sessions" */'@/pages/users/sessions.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__users__login-history" */'@/pages/users/login-history.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__audit-logs__index" */'@/pages/audit-logs/index.tsx')),
'11': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
},
  };
}
